# Generated by Django 4.1 on 2024-02-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_themes_content_themes_created_at_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themes',
            name='content',
        ),
        migrations.RemoveField(
            model_name='themes',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
